<?php

use Illuminate\Database\Seeder;

class GatherPlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('gather_place')->insert([
            'name' => 'パミスストーン',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 7,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '15, 27',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'エボニー原木',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 5,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '25, 25',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ハニーレモン/種',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 7,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '26, 32',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ソフトスピナッチ',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 6,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '31, 13',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ブラッドオレンジ他',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 8,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '28, 25',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ラノシアリーキ他',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 46,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '33, 27',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'アプリコット',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 5,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '17, 16',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'パイナップル/種',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 7,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '31, 26',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ゼーメルトマト/種',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 7,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '17, 28',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ラノシア岩塩',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 7,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '17, 34',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ルビー/サファイア原石',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 6,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '23, 21',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ラノシアンソイルG3',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 5,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '23, 26',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '生マユ',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 14,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '21, 26',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ティノルカ茶葉',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 13,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '15, 21',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '黒衣香木',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 15,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '18, 23',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '緋樹液',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 16,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '15, 26',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'トリリウム',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 14,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '19, 17',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '霊性岩/ｼｭﾗｳﾄﾞｿｲﾙG3',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 15,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '26, 18',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '高級黒衣香木',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 13,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '30, 19',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'サイプレス原木',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 13,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '24, 31',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ローズマリー',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 14,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '22, 30',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'トリリウムの球根',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 14,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '12, 24',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '強霊性岩',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 23,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '26, 18',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '鉄重石/他',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 25,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '16, 20',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '自然金/他',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 22,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '25, 15',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '白金鉱',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 24,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '15, 12',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '金砂',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 23,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '27, 22',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ザナラーンソイルG3',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 21,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '19, 28',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '金鉱',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 23,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '29, 24',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ブラックトリュフ',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 23,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '12, 16',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'バジリスクの初卵',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 25,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '23, 22',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '闇鉄鉱',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 28,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '27, 19',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'スプルース原木',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 28,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '31, 14',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ヴァンパイアプラント',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 28,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '27, 23',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'サベネアミスルトゥ',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 28,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '7, 11',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '星性岩',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 28,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '22, 24',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'クラスター各種',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 30,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '28, 12',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'クラスター各種',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 30,
            'level' => 50,
            'elapsed_time' => '03:00:00',
            'memo' => '',
            'place_point' => '31, 14',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'オレガノ/他刻限',
            'class_id' => 2,
            'gather_place_type_id' => 2,
            'area_id' => 29,
            'level' => 60,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '10, 14',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'アストラルグラベル/他伝説',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 29,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '33, 18',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '重石華',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 29,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '11, 10',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '黄銅鉱',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 29,
            'level' => 50,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '28, 22',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '雪綿/他伝説',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 29,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '23, 21',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'カベイジの野菜',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 29,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '9, 10',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'クルザス茶葉/他',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 29,
            'level' => 55,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '32, 20',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ライトニンググラベル/他刻限',
            'class_id' => 1,
            'gather_place_type_id' => 2,
            'area_id' => 29,
            'level' => 60,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '21, 26',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'アダマン鉱',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 32,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '23, 6',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'スイートアーモンド',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 31,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '6, 6',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ワットル樹皮',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 32,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '23, 8',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '星綿',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 32,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '8, 29',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '金雲母',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 31,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '38, 37',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '輝金鉱',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 32,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '6, 16',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'アバラシアミスルトゥ/他',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 31,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '33, 23',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '菱亜鉛鉱/他伝説',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 31,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '37, 14',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'レッドアルメン',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 32,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '36, 16',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'アバラシア岩塩/他',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 31,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '8, 9',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'オレガノ/他刻限',
            'class_id' => 2,
            'gather_place_type_id' => 2,
            'area_id' => 31,
            'level' => 60,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '23, 12',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ドラヴァニアミスルトゥ',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 36,
            'level' => 55,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '25, 7',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'チーク原木',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 35,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '8, 26',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '光霊銀鉱/皇金鉱',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 36,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '8, 33',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '赤銅鉱/赤鉄鉱',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 35,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '33, 30',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'オールドワールドフィグ',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 34,
            'level' => 50,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '26, 12',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ファイアグラベル/他刻限',
            'class_id' => 1,
            'gather_place_type_id' => 2,
            'area_id' => 34,
            'level' => 60,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '17, 27',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '赤玉土/他刻限',
            'class_id' => 2,
            'gather_place_type_id' => 2,
            'area_id' => 35,
            'level' => 60,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '12, 19',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'アストラルフラワー',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 36,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '17, 36',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'クラウドバナナ/モリーユ',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 35,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '16, 37',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'イエロー/グリーンクォーツ',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 36,
            'level' => 55,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '33, 23',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ブルークォーツ',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 35,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '12, 15',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ノーブルセージ',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 34,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '34, 28',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ファイアグラベル/他刻限',
            'class_id' => 1,
            'gather_place_type_id' => 2,
            'area_id' => 35,
            'level' => 60,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '25, 24',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '赤玉土/他刻限',
            'class_id' => 2,
            'gather_place_type_id' => 2,
            'area_id' => 34,
            'level' => 60,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '10, 32',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '樹液結晶/カンファー古木',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 36,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '10, 9',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '沸石',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 35,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '16, 31',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '輝銅鉱/黄鉄鉱/褐鉄鉱',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 34,
            'level' => 55,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '28, 18',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ブラウンマッシュルーム',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 36,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '12, 37',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'スナーブルベリー',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 35,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '38, 21',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ファイアグラベル/他刻限',
            'class_id' => 1,
            'gather_place_type_id' => 2,
            'area_id' => 36,
            'level' => 60,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '29, 19',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '赤玉土/他刻限',
            'class_id' => 2,
            'gather_place_type_id' => 2,
            'area_id' => 36,
            'level' => 60,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '20, 30',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'アラミゴ塩',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 40,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '21, 29',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'アルマンディン',
            'class_id' => 1,
            'gather_place_type_id' => 2,
            'area_id' => 40,
            'level' => 70,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '13, 16',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'トリフェーン原石',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 38,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '24, 7',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ジャムメルジンジャー',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 40,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '8, 8',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'トレヤの枝',
            'class_id' => 2,
            'gather_place_type_id' => 2,
            'area_id' => 40,
            'level' => 70,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '28, 10',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ハロードバジル',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 39,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '24, 16',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ビーチの枝',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 38,
            'level' => 60,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '11, 18',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'トレヤ原木',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 40,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '11, 13',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ロードナイト原石',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 39,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '26, 12',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'クロマイト',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 39,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '15, 34',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'スタースピネル原石',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 43,
            'level' => 65,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '15, 4',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '藍麻',
            'class_id' => 2,
            'gather_place_type_id' => 3,
            'area_id' => 45,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '19, 10',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'オサードプラム',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 45,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '27, 16',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'アズライト原石',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 45,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '4, 24',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '清金鉱',
            'class_id' => 1,
            'gather_place_type_id' => 3,
            'area_id' => 44,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '21, 10',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'インペリアルジェード原石',
            'class_id' => 1,
            'gather_place_type_id' => 1,
            'area_id' => 44,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '29, 9',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '蓮根',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 44,
            'level' => 70,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '28, 7',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '黄土',
            'class_id' => 2,
            'gather_place_type_id' => 2,
            'area_id' => 45,
            'level' => 70,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '16, 28',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'タケノコ',
            'class_id' => 2,
            'gather_place_type_id' => 1,
            'area_id' => 44,
            'level' => 65,
            'elapsed_time' => '02:00:00',
            'memo' => '',
            'place_point' => '28, 25',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ショール',
            'class_id' => 1,
            'gather_place_type_id' => 2,
            'area_id' => 45,
            'level' => 70,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '29, 16',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'パーライト',
            'class_id' => 1,
            'gather_place_type_id' => 2,
            'area_id' => 44,
            'level' => 70,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '37, 19',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => '風茶葉',
            'class_id' => 2,
            'gather_place_type_id' => 2,
            'area_id' => 44,
            'level' => 70,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '22, 13',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_place')->insert([
            'name' => 'ライトニンググラベル/他刻限',
            'class_id' => 1,
            'gather_place_type_id' => 2,
            'area_id' => 31,
            'level' => 60,
            'elapsed_time' => '04:00:00',
            'memo' => '',
            'place_point' => '34, 30',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
    }
}
