<?php

use Illuminate\Database\Seeder;

class GatherItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('gather_item')->insert([
            'name' => 'ファイアクラスター',
            'level' => 50,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '1.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アイスクラスター',
            'level' => 50,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '2.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ウィンドクラスター',
            'level' => 50,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '3.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アースクラスター',
            'level' => 50,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '4.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ライトニングクラスター',
            'level' => 50,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '5.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ウォータークラスター',
            'level' => 50,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '6.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '金鉱',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '7.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '闇鉄鉱',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '8.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'コブランラーヴァ',
            'level' => 50,
            'star' => 1,
            'is_limit' => 1,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '9.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '無属性クリスタル',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '10.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'グレガリアスワーム',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '11.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '鉄重石',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '12.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ルビー原石',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => 'normalGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ダイヤモンド原石',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => 'normalGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'エメラルド原石',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => 'normalGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'トパーズ原石',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => 'normalGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アイオライト原石',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => 'normalGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'サファイア原石',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => 'normalGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '自然金',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '19.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ダークマタークラスター',
            'level' => 50,
            'star' => 2,
            'is_limit' => 1,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '20.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '黄銅鉱',
            'level' => 50,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '21.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '白金鉱',
            'level' => 50,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '22.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'バジリスクの初卵',
            'level' => 50,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '23.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '星性岩',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '24.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '金砂',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => 'goldSand.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ラノシア岩塩',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '26.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '霊性岩',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '27.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ラノシアンソイルG3',
            'level' => 50,
            'star' => 1,
            'is_limit' => 1,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '28.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'シュラウドソイルG3',
            'level' => 50,
            'star' => 1,
            'is_limit' => 1,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '29.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ザナラーンソイルG3',
            'level' => 50,
            'star' => 1,
            'is_limit' => 1,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '30.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '強霊性岩',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '31.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'パミスストーン',
            'level' => 50,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => 'stone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'パイナップル',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '33.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'スプルース原木',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '34.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'サベネアミスルトゥ',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => 'plant.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ヴァンパイアプラント',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => 'plant.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'パイナップルの種',
            'level' => 50,
            'star' => 1,
            'is_limit' => 1,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '37.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '黒衣香木',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '38.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アプリコット',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '39.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ブラッドオレンジ',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '40.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'バンブー材',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '41.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '高級黒衣香木',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '42.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '緋樹液',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '43.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'エボニー原木',
            'level' => 50,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '44.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'サイプレス原木',
            'level' => 50,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '45.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ブラックトリュフ',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '46.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ハニーレモン',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '47.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '生マユ',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '48.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'トリリウム',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '49.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'トリリウムの球根',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '50.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ミニマンドラゴラ',
            'level' => 50,
            'star' => 1,
            'is_limit' => 1,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '51.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ゼーメルトマトの種',
            'level' => 50,
            'star' => 1,
            'is_limit' => 1,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '52.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ハニーレモンの種',
            'level' => 50,
            'star' => 1,
            'is_limit' => 1,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '53.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'マズラヤの野草',
            'level' => 50,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '54.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ラノシアリーキ',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '55.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ソフトスピナッチ',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '56.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '水鳥の羽根',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '57.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ティノルカ茶葉',
            'level' => 50,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '58.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'オールドワールドフィグ',
            'level' => 50,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '59.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'オールドワールドフィグの種',
            'level' => 50,
            'star' => 3,
            'is_limit' => 1,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '60.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ローズマリー',
            'level' => 50,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '61.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '黄鉄鉱',
            'level' => 51,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '62.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '輝銅鉱',
            'level' => 53,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '63.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '褐鉄鉱',
            'level' => 54,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '64.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'イエロークォーツ',
            'level' => 52,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '65.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'グリーンクォーツ',
            'level' => 55,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '66.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ポルチーニ',
            'level' => 51,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '67.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ドラヴァニアミスルトゥ',
            'level' => 54,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => 'plant.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'プチキャベツ',
            'level' => 52,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '69.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'プチキャベツの種',
            'level' => 52,
            'star' => 0,
            'is_limit' => 1,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '70.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'クルザス茶葉',
            'level' => 53,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '71.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'クルザス茶樹の種',
            'level' => 53,
            'star' => 0,
            'is_limit' => 1,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '72.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'チャイブ',
            'level' => 55,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '73.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '赤鉄鉱',
            'level' => 57,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '74.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '赤銅鉱',
            'level' => 59,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '75.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アダマン鉱',
            'level' => 60,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '76.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'トリフェーン原石',
            'level' => 60,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => 'yellowGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アバラシア岩塩',
            'level' => 56,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '78.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ファイアグラベル',
            'level' => 56,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '79.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ライトニンググラベル',
            'level' => 56,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '80.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'レッドクォーツ',
            'level' => 58,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '81.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '強火成岩',
            'level' => 58,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => 'redGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '強雷性岩',
            'level' => 58,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => 'purpleGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'レイディアントファイアグラベル',
            'level' => 60,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '84.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'レイディアントライトニンググラベル',
            'level' => 60,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '85.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'レイディアントアストラルグラベル',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '86.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ヘヴンズドレモン',
            'level' => 56,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '87.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'クラウドバナナ',
            'level' => 57,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '88.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アバラシアミスルトゥ',
            'level' => 58,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => 'plant.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'モリーユ',
            'level' => 59,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '90.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ビーチの枝',
            'level' => 60,
            'star' => 2,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '91.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'オレガノ',
            'level' => 56,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '92.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '赤玉土',
            'level' => 56,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '93.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'スペアミント',
            'level' => 58,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '94.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ピートモス',
            'level' => 58,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '95.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'カベイジの野菜',
            'level' => 60,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '96.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'クラリーセージ',
            'level' => 60,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '97.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '黒土',
            'level' => 60,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '98.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'メネフィナローレル',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '99.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '皇金鉱',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '100.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '光霊銀鉱',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '101.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'レッドアルメン',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '102.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '菱亜鉛鉱',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '103.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'メテオライト',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '104.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '重石華',
            'level' => 60,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '105.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '輝金鉱',
            'level' => 60,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '106.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'バイオレットクォーツ',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '107.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アストラルグラベル',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '108.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ブルークォーツ',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '109.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '金雲母',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '110.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '沸石',
            'level' => 60,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '111.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'カンファー古木',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '112.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '樹液結晶',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '113.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'スイートアーモンド',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '114.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ワットル樹皮',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '115.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ブラウンマッシュルーム',
            'level' => 60,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '116.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'チーク原木',
            'level' => 60,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '117.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ドラヴァニアパプリカ',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '118.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'バニラビーンズ',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '119.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '雪綿',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '120.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'スナーブルベリー',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '121.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アストラルフラワー',
            'level' => 60,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '122.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ノーブルセージ',
            'level' => 60,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '123.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '星綿',
            'level' => 60,
            'star' => 3,
            'is_limit' => 0,
            'patch' => '3.x',
            'memo' => '',
            'icon' => '124.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'スタースピネル原石',
            'level' => 63,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => 'purpleGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'タケノコ',
            'level' => 63,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '126.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ショール',
            'level' => 66,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '127.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アズライト原石',
            'level' => 66,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => 'blueGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'インペリアルジェード原石',
            'level' => 68,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '129.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ロードナイト原石',
            'level' => 70,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => 'redGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アルマンディン',
            'level' => 70,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => 'redGemstone.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'パーライト',
            'level' => 66,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '132.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アラミゴ塩',
            'level' => 69,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '133.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'オサードプラム',
            'level' => 70,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '134.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'トレヤの枝',
            'level' => 70,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '135.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '蓮根',
            'level' => 66,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '136.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '黄土',
            'level' => 66,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '137.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '風茶葉',
            'level' => 66,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '138.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ジャムメルジンジャー',
            'level' => 68,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '139.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ハロードバジル',
            'level' => 70,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '140.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'クロマイト',
            'level' => 70,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '141.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '清金鉱',
            'level' => 70,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '142.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'トレヤ原木',
            'level' => 70,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '143.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => '藍麻',
            'level' => 70,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '4.0',
            'memo' => '',
            'icon' => '144.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ゼーメルトマト',
            'level' => 50,
            'star' => 0,
            'is_limit' => 0,
            'patch' => '2.x',
            'memo' => '',
            'icon' => '145.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'ギラバニア清水',
            'level' => 70,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '4.1',
            'memo' => '',
            'icon' => 'water.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('gather_item')->insert([
            'name' => 'アジム綿花',
            'level' => 70,
            'star' => 1,
            'is_limit' => 0,
            'patch' => '4.1',
            'memo' => '',
            'icon' => '147.png',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
    }
}
