# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
machine:
  timezone: /usr/share/zoneinfo/Asia/Tokyo
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: circleci/mysql:5.7.21-ram

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Library
          command: sudo apt-get install -y libpng-dev libjpeg-dev

      - run:
          name: Install PHP extensions
          command: |
            sudo docker-php-ext-install pdo_mysql
            sudo docker-php-ext-configure gd --with-png-dir=/usr/include --with-jpeg-dir=/usr/include
            sudo docker-php-ext-install gd

      - run:
          name: composer self-update
          command: |
            sudo composer self-update

      - run:
          name: Display versions
          command: |
            php -v
            composer --version

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Compoile
          command: npm run prod

      - run:
          name: Setup Environment
          command: |
            cp .env.circle .env
            php artisan key:generate
            mv .env .env.testing
            php artisan passport:keys

      - run:
          name: Run PhpUnit
          command: ./vendor/bin/phpunit

      - run:
          name: Run Phpcs
          command: ./vendor/bin/phpcs --standard=./phpcs_ruleset.xml app tests
